Dataset:
  Type: MuapWave
  Batch: 32
  num_conds: 6
  num_workers: 2
  Train:
    Type: train_real
  Test:
    Type: test_real
Training:
  num_epoch: 50
  anneal_kld: True
  anneal_type: logistic
  anneal_iters: 90000
Eval:
  snap_shot: 5
Optimizer:
  G: 0.00001
  D: 0.00001
Model:
  Generator:
    Latent: 16
    num_conds: 6
    Enc:
      num_layers: 5
      in_channel: 1
      out_channel: 256
      hidden_channels:
      - 16
      - 32
      - 64
      - 128
      kernel: 3
      stride:
      - 2
      - 2
      - 2
      - [2, 1, 1]
      - 1
      pad: 1
      final_dim: [6, 2, 4]
    Dec:
      cond_proj_dim: 64
      pre_conv: [3, 1, 1]
      num_pre_conv: 4
      num_rescale: 2
      rescale:
      - [24, 3, 8]
      - [96, 5, 16]
      up_conv:
        hidden_channels:
        - 128
        - 64
        - 32
        - 16
        args: [3, 1, 1]
      final_interpolate: [96, 10, 32]
  Discriminator:
    negative_slope: .03
    num_conds: 6
    num_layers: 5
    in_channel: 1
    residual: True
    hidden_channels:
    - 16
    - 32
    - 64
    - 128
    out_channel: 256
    kernel: 3
    stride:
    - 2
    - 2
    - 2
    - [2, 1, 1]
    - 1
    pad: 1
    final_dim: [6, 2, 4]
Loss:
  w_gan: 10.
  w_kld: 0.1
  w_cycle: 5